"""create db

Revision ID: 6eaa99d0190a
Revises: 
Create Date: 2021-09-09 19:16:15.765546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaa99d0190a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_url', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=100), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_log_created'), 'api_log', ['created'], unique=False)
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_log_created'), 'error_log', ['created'], unique=False)
    op.create_table('x_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_currency', sa.Integer(), nullable=True),
    sa.Column('to_currency', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_x_rate_from_currency'), 'x_rate', ['from_currency'], unique=False)
    op.create_index(op.f('ix_x_rate_to_currency'), 'x_rate', ['to_currency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_x_rate_to_currency'), table_name='x_rate')
    op.drop_index(op.f('ix_x_rate_from_currency'), table_name='x_rate')
    op.drop_table('x_rate')
    op.drop_index(op.f('ix_error_log_created'), table_name='error_log')
    op.drop_table('error_log')
    op.drop_index(op.f('ix_api_log_created'), table_name='api_log')
    op.drop_table('api_log')
    # ### end Alembic commands ###
