"""errorlogapilog

Revision ID: b5ff2e8e469f
Revises: 8f55a04dbde5
Create Date: 2021-09-08 22:58:59.125259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ff2e8e469f'
down_revision = '8f55a04dbde5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_url', sa.String(length=255), nullable=True),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=100), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_log_created'), 'api_log', ['created'], unique=False)
    op.create_table('error_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_data', sa.Text(), nullable=True),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_log_created'), 'error_log', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_error_log_created'), table_name='error_log')
    op.drop_table('error_log')
    op.drop_index(op.f('ix_api_log_created'), table_name='api_log')
    op.drop_table('api_log')
    # ### end Alembic commands ###
